[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Generative AI Project"
version = "1.0.0"
authors = [{name = "Yee Jun Ow"}]
readme = "README.md"
requires-python = ">= 3.12"

[tool.dagster]
module_name = "src"